/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.nwsummit.games.mines;

import org.testng.annotations.*;
import static org.testng.Assert.*;

public class MinesTest {
    @Test public void appHasAGreeting() {
        Mines classUnderTest = new Mines();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
